project_name: production-app

modules:
  project:
    selected: true
    project_name: production-app
    project_id: my-gcp-project-prod-123450
    project_deletion_policy: DELETE
    enabled_apis:
      - compute.googleapis.com
      - sqladmin.googleapis.com
      - run.googleapis.com
      - vpcaccess.googleapis.com
      - secretmanager.googleapis.com
      - cloudresourcemanager.googleapis.com
      - servicenetworking.googleapis.com
      - monitoring.googleapis.com
      - logging.googleapis.com

  network:
    selected: true
    region: us-central1
    ip_cidr_range: 10.0.0.0/16

  firewall:
    selected: true
    protocol_type: tcp
    allowed_ports_sql: ['5432', '443']
    target_tags_sql: ["sql"]
    source_ranges:  ["0.0.0.0/0"]


  sql:
    selected: true
    db_version: POSTGRES_15
    db_tier: db-custom-2-7680
    sql_user: teamavail

  secrets:
    selected: true
    secret_id: db_password

  cloudrun:
    selected: true
    cloudrun_name: production-backend-api
    image_name: gcr.io/my-gcp-project-prod-12345/backend-api:v1.2.3
    container_name: backend-api-container
    container_port: 8080

  vpc_connector:
    selected: true
    ip_cidr_range_connector: 10.8.0.0/28

  iam:
    selected: true
    service_account_id: cloudrun-sa-prod
    display_name: Cloud Run Service Account
    roles:
      - roles/cloudsql.client
      - roles/secretmanager.secretAccessor
      - roles/logging.logWriter
      - roles/monitoring.metricWriter

  load-balancer:
    selected: true

  monitoring:
    selected: true
    alert_email: aliashmawy595@gmail.com